################################################################################
# PRE-TRAINING EXPERIMENT PARAMS
################################################################################
base:
  seed: 'na'
  use_all: False
  cuda: 'na'

models: 'na'

training:
  epochs: 1 # 300
  loss: 'weighted' # weighted or normal
  batch_type: 'normal' #normal or trans  
  batch_size: 80
  num_workers: 8

hyper:
  initial_lr: 0.0001
  # The lowest lr that is ever hit                                                             
  min_lr: 0.0001
  # Patience for val loss
  patience: 100000
  # Factor of lr reduction-new_lr = lr*factor
  factor: 0.1        
  # Number of epochs to warm up for before using scheduler
  scheduler_warm_up: 10


data: 'na'

split: 'na'