################################################################################
# PRE-TRAINING EXPERIMENT PARAMS
################################################################################
base:
  seed: 0
  task_type: 'AudioSet_pretrain_'
  use_all: True # do we want to use all data in teh dataset for pre-train
  cuda: 0

models: ['Hybrid'] # Wan to use the hybrid globalCRNN model for training

training:
  epochs: 1
  loss: 'weighted' # weighted or normal
  batch_type: 'normal' #normal or trans  
  batch_size: 10
  num_workers: 4

hyper:
  initial_lr: 0.0001
  T_max: 1
  min_lr: 0

data:
  name: 'AudioSet' # name must also be present in DatasetSetup if using some split of dataset
  norm: 'global' #global/per_sample/channel
  type: 'spec' # currently only coded for fixed length spectrograms
  fixed: False # we dont want to used some fixed split of audioset's classes 
  data_path: 'C:/Users/user/Documents/Datasets/AudioSet/AS_spec_reduced_'

split:
  train: 0.7
  val: 0.1
  test: 0.2